name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 23 * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "dreamhunter2333@gmail.com"
          git config --local user.name "jimu333"
          git remote set-url origin https://jinmu333:${{ secrets.GITHUB_TOKEN }}@github.com/jinmu333/auto-green.git
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
